version: '3.8'

services:
  web:
    build: 
      context: ./project
      dockerfile: Dockerfile.prod
    container_name: web_deploy_prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/project/web/staticfiles
      - media_volume:/home/project/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./env/prod/project.env

  nginx:
    build: ./nginx
    container_name: nginx_deploy_prod
    volumes:
      - static_volume:/home/project/web/staticfiles
      - media_volume:/home/project/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: