version: '3.8'

services:
  web:
    build: ./project
    container_name: web_deploy_dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8000:8000
    env_file:
      - ./env/dev/project.env
    depends_on:
      - db
